
--SQL Sorgusundan Gelen Deðeri Deðiþkene Atama
Declare @TOTALPRICE AS INT
Declare @ROWCOUNT AS INT
Declare @TOTALAMOUNT AS INT
Declare @CUSTOMERCOUNT AS INT

USE GYSALES
Select @TOTALPRICE=SUM(TOTALPRICE),@ROWCOUNT=count(*),
@TOTALAMOUNT=sum(AMOUNT),@CUSTOMERCOUNT=COUNT(CUSTOMERID) from SALES

SELECT @TOTALAMOUNT TOTALAMOUNT,@ROWCOUNT ROWCOUNT_,@TOTALPRICE TOTALPRICE,@CUSTOMERCOUNT CUSTOMERCOUNT