
--Deðiþkene Varsayýlan Deðer Atama(DECLARE DEFAULT VARIABLE)
USE GYSALES
Declare @CITY2 AS VARCHAR(100) = 'Ýzmir',
		@BEGDATE2 AS DATE = '20220401',
		@ENDDATE2 AS DATE = '20220501'
SET @CITY2 = 'BURSA'
SET @CITY2 = 'ANKARA'




SELECT * FROM SALES
	WHERE CITY = @CITY2 AND
			DATE_ BETWEEN @BEGDATE2 AND @ENDDATE2-- Output: 1516 row @CITY2 = 'ANKARA'
			-- ÝZMÝR<BURSA<ANKRA yetki sýrasý

			