
--SQL Sorgusuna Deðiþken Gönderme
USE GYSALES
Declare @CITY AS VARCHAR(100),@BEGDATE AS DATE,@ENDDATE AS DATE
SET @CITY = 'BURSA'
SET @BEGDATE = '20220401'
SET @ENDDATE = '20220501'


SELECT * FROM SALES
	WHERE CITY = @CITY AND
		  DATE_ BETWEEN @BEGDATE AND @ENDDATE-- Output: 1516 row