
DECLARE  @BEGDATE AS DATETIME = '2022-04-01',
		 @ENDDATE AS DATETIME = '2022-05-01',
		 @CITY AS VARCHAR(100)= 'ANKARA,BURSA,BÝLECÝK'


select CITY,SUM(TOTALPRICE)TOTALPRICE from LAB07
	where CITY IN ((SELECT * FROM string_split(@CITY,',')))
		  AND
		  DATE_ BETWEEN @BEGDATE AND @ENDDATE
	GROUP BY CITY
	ORDER BY 2