
DECLARE @NAME AS VARCHAR(100),@SURNAME AS VARCHAR(100),
		@G AS CHAR(1),@CITY AS VARCHAR(100),@BIRTHDATE AS VARCHAR(100)
SET @BIRTHDATE = CONVERT(varchar(100),CONCAT(1950+FLOOR(RAND()*50),'.',FLOOR(1+RAND()*11),'.',FLOOR(1+RAND()*30)))

select @CITY= CITY from CITIES ORDER BY NEWID()	
select @NAME= NAME_, @G= GENDER from NAMES ORDER BY NEWID()	
select @SURNAME= SURNAME from SURNAMES ORDER BY NEWID()


--YONTEM 2
DECLARE @NAMESURNAME AS VARCHAR(100),@RAND AS INT = 1+RAND()*609--	1-610 RASTGELE SAYI URETIR
select @NAME= NAME_, @G= GENDER from NAMES WHERE ID= @RAND
SET @RAND = 1+ RAND()*797
select @SURNAME= SURNAME from SURNAMES WHERE ID= @RAND
SET @RAND = RAND()*365*50 --50 Yýl dedi çünkü (1950-2000 arasýnda)
SET @BIRTHDATE = CONVERT(VARCHAR,DATEADD(DAY,@RAND,'1950-01-01'),104)
SET @NAMESURNAME = @NAME+' '+@SURNAME
SELECT @NAME NAME_,@SURNAME SURNAME,@NAMESURNAME NAMESURNAME,@G GENDER,@CITY CITY,@BIRTHDATE BIRTHDATE


