
--> CONCAT()
		SELECT 'MERHABA' + ' ' + 'ARKADASLAR' + ' ' + 'NASILSINIZ'

		SELECT CONCAT('MERHABA', ' ', 'ARKADASLAR', ' ', 'NASILSINIZ')
		SELECT CONCAT_WS(' ','MERHABA', 'ARKADASLAR', 'NASILSINIZ') --> MERHABA ARKADASLAR NASILSINIZ
		SELECT CONCAT_WS('MERHABA', 'ARKADASLAR', 'NASILSINIZ') --> ARKADASLARMERHABANASILSINIZ
--> LEN()
		SELECT LEN('MERHABA' + ' ' + 'ARKADASLAR' + ' ' + 'NASILSINIZ') -- 29
--> LEFT() RIGHT()
		SELECT LEFT('PORTAKAL',3)--POR
		SELECT RIGHT('PORTAKAL',5)--TAKAL

--> UPPER() LOWER()
		SELECT UPPER('PoRTAkal')--PORTAKAL
		SELECT LOWER('PoRTAkal')--portakal

--> REVERSE()
		SELECT REVERSE('MERHABA')--ABAHREM
		SELECT REVERSE('EY EDÝP ADANADA PÝDE YE')--EY EDIP ADANADA PIDE YE

--> REPLACE()
		SELECT REPLACE('YÖNETÝM BÝLGÝ SÝSTEMLERÝ','BÝLGÝ','BÝLÝÞÝM')--YÖNETIM BILISIM SISTEMLERI
		-- TURKCE KARAKTERE GORE SADECE Ý DE UYUM SAÐLAMAZ Ý YÝ I YA ÇEVÝRÝR

--> TRIM() LTRIM() RTRIM()
		SELECT TRIM('    MERHABA ARKADAÞLAR   ')--MERHABA ARKADASLAR;
		SELECT LTRIM('    MERHABA ARKADAÞLAR   ')--MERHABA ARKADASLAR   ;
		SELECT RTRIM('    MERHABA ARKADAÞLAR   ')--    MERHABA ARKADASLAR;

--> SUBSTRING()
		SELECT SUBSTRING('MERHABA ARKADAÞLAR',9,100)--ARKADASLAR;
--> CHARINDEX()
		SELECT CHARINDEX('arkadaþlar','MERHABA ARKADAÞLAR')
		-- Büyük harf küçük harf duyarlýlýðý yok
		SELECT CHARINDEX('e','MERHABA ARKADAÞLAR',3)-- 0 
		-- 3 kýsmý baþlýyacaðý indisi belirtir