SELECT CITY,

(SELECT ROUND(SUM(LINETOTAL),0) TUTAR FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE CATEGORY1 = 'GIDA' AND A.CITYID=C.ID) TUTAR,

(SELECT ROUND(SUM(LINETOTAL),0) TUTAR FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE CATEGORY1 = 'DETERJAN TEMÝZLÝK' AND A.CITYID=C.ID) TEMÝZLÝK

FROM CITIES C

