--USE GYSALES_RDMS_FULL
/**
SELECT U.ID ORDERID,U.USERNAME_,U.NAMESURNAME,
O.DATE_ ORDERDATE,O.TOTALPRICE,
A.POSTALCODE,A.ADDRESSTEXT,
CNTRY.COUNTRY,
C.CITY,T.TOWN,D.DISTRICT,
I.ITEMCODE,I.ITEMNAME,I.BRAND,I.CATEGORY1,I.CATEGORY2,
OD.AMOUNT,OD.UNITPRICE,OD.LINETOTAL


FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN ITEMS I ON I.ID=OD.ITEMID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
JOIN DISTRICTS D ON D.ID= A.DISTRICTID
JOIN COUNTRIES CNTRY ON CNTRY.ID = A.COUNTRYID
*/

--https://gelecegiyazanlar.turkcell.com.tr/konu/egitim/sql-ile-veritabani-sorgulama-giris-301/view-olusturma

--REVIZYON 1 HEADERLARI TURKCELESTIR

--REVIZYON 2 AYLARIN ISIMLERINI GETIR (TURKÇE OLARAK)

--REVIZYON 3 BOLGELERI DE GETIR

--REVIZYON 4 SIPARISID IFADESI SIPARISNO ILE DEGÝSTÝRÝLDÝ


/**
USE GYSALES_RDMS_FULL
SET LANGUAGE turkish

SELECT U.ID SIPARISNO, U.USERNAME_ KULLANICIADI,U.NAMESURNAME ADSOYAD,
O.DATE_ SIPARISTARIHI, DATENAME(MONTH, O.DATE_) AY, O.TOTALPRICE TUTAR,
A.POSTALCODE POSTAKODU,A.ADDRESSTEXT ACIKADRES,
CNTRY.COUNTRY ULKE, C.REGION BOLGE,
C.CITY SEHIR,T.TOWN ILCE,D.DISTRICT MAHALLE,
I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.BRAND MARKA,I.CATEGORY1 KATEGORI1,I.CATEGORY2 KATEGORI2,
OD.AMOUNT MIKTAR,OD.UNITPRICE BIRIMUCRET,OD.LINETOTAL SATIRTUTARI


FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN ITEMS I ON I.ID=OD.ITEMID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
JOIN DISTRICTS D ON D.ID= A.DISTRICTID
JOIN COUNTRIES CNTRY ON CNTRY.ID = A.COUNTRYID
*/
-- HER SEFERINDE SORGUYU EXCELE GIRMEK YERINE VIEW ATAMASI YAPILIR

ALTER VIEW VWORDERS 
AS
-- VIEW OLUSTURURKEN (CREATE), DUZENLERKEN(ALTER), SILERKEN ISE(DROP)
SELECT U.ID SIPARISNO, U.USERNAME_ KULLANICIADI,U.NAMESURNAME ADSOYAD,
O.DATE_ SIPARISTARIHI, 
CASE
	WHEN  MONTH(O.DATE_)<10 THEN CONCAT(0,MONTH(O.DATE_),'.',LEFT(DATENAME(MONTH,O.DATE_),3))
	ELSE CONCAT(MONTH(O.DATE_),'.',LEFT(DATENAME(MONTH,O.DATE_),3))
END TARIH
, O.TOTALPRICE TUTAR,
A.POSTALCODE POSTAKODU,A.ADDRESSTEXT ACIKADRES,
CNTRY.COUNTRY ULKE, C.REGION BOLGE,
C.CITY SEHIR,T.TOWN ILCE,D.DISTRICT MAHALLE,
I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.BRAND MARKA,I.CATEGORY1 KATEGORI1,I.CATEGORY2 KATEGORI2,
OD.AMOUNT MIKTAR,OD.UNITPRICE BIRIMUCRET,OD.LINETOTAL SATIRTUTARI


FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN ITEMS I ON I.ID=OD.ITEMID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
JOIN DISTRICTS D ON D.ID= A.DISTRICTID
JOIN COUNTRIES CNTRY ON CNTRY.ID = A.COUNTRYID

-- REVIZYONDA SADECE SQL KISMINDA YAPILIR EXCELI YENILEMEK YETERLIDIR
--REVIZYON 1 03.MAR ÝFADESININ HEADERI (BAÞLIGI) AY OLARAK KALMIS ONU TARIH ILE DEGISTIR


