--> DateTime Fonksiyonlarý
/**		select GETDATE() 'GETDATE', --: Anlýk olarak sunucudan Tarih getirir (ex: 2024-05-03 14:54:04.800) DateTime formatýnda
		SYSDATETIME() 'SYSDATETIME', --: DateTime 2 formatýnda(daha hassas)
		SYSDATETIMEOFFSET() 'SYSDATETIMEOFFSET', --: Ek olarak time zone degerini verir(Istanbul +3 saat)

		SYSUTCDATETIME() 'SYSUTCDATETIME', --: Greenwich deki saati getirir (3 saat geri)
		CURRENT_TIMESTAMP 'CURRENT_TIMESTAMP', --: getdate() e benzer
		GETUTCDATE() 'GETUTCDATE' --: Greenwich deki utc tarihi verir(3 saat geri)
*/
--> DatePart Fonksiyonlarý
/**		SELECT DATEPART(YEAR,GETDATE())YEAR_,
		DATEPART(MONTH,GETDATE())MONTH_,
		DATEPART(DAY,GETDATE())DAY_,

		DATEPART(HOUR,GETDATE())HOUR_,
		DATEPART(MINUTE,GETDATE())MINUTE_,
		DATEPART(SECOND,GETDATE())SECOND_,
		DATEPART(MILLISECOND,GETDATE())MILISECOND_,

		DATEPART(D,GETDATE())D_,	--:DAY
		DATEPART(DAYOFYEAR,GETDATE())DAYOFYEAR_,	--: KAÇINCI GÜN
		DATEPART(DD,GETDATE())DD_,	--: DAY
		DATEPART(DW,GETDATE())DW_,	--: HAFTANIN KAÇINCI GÜNÜ (Ýngiliz standartýna göre)(cuma)
		DATEPART(ISO_WEEK,GETDATE())ISOWEEK_,	--: Kaçýncý hafta
		DATEPART(WEEK,GETDATE())WEEK_,
		DATEPART(QUARTER,GETDATE())QUARTER_,	--: Kaçýncý Çeyrek
 */
 --> DatePart Fonksiyonlarý
/**		 SELECT DATENAME(YEAR,GETDATE())YEAR_,
		 DATENAME(MONTH,GETDATE())MONTH_,
		 DATENAME(DAY,GETDATE())DAY_, --: AY ÝÇÝNDEKÝ GÜN NUMARASINI GETÝRÝ AYIN 3 Ü GÝBÝ
		 DATENAME(DW,GETDATE())DW_, --:firday/cuma
		 DATENAME(HOUR,GETDATE())HOUR_,
		 DATENAME(MINUTE,GETDATE())MINUTE_,
		 DATENAME(SECOND,GETDATE())SECOND_

		  --->türkçeye çevirmek için 
		--SET LANGUAGE Turkish
*/
-->DateFromParts Fonksiyonlarý
/**		SELECT DATEFROMPARTS(2024,05,03) DATEFROMPARTS_,
		DATETIMEFROMPARTS(2024,05,03,23,59,59,000) DATETIMEFROMPARTS_, 
		TIMEFROMPARTS(15,28,59,4,5)TIMEFROMPARTS_ --: Time deðerinin saniye hassasiyetine göre getirmesi ayarlanýr
*/
--> Day/Month/Year Fonksiyonlarý
/**		SELECT DATEPART(YEAR,GETDATE()),
		YEAR(GETDATE())YEAR_,
		MONTH(GETDATE())MONTH_,
		DAY(GETDATE())DAY_,
		DATEPART(HOUR,GETDATE())HOUR_,
*/
-->DateDiff Fonksiyonlarý
/**		 SELECT DATEDIFF(YEAR,'2002-03-08',GETDATE())YIL_FARK,
		 DATEDIFF(MONTH,'2002-03-08',GETDATE())AY_FARK,
		 DATEDIFF(DAY,'2002-03-08',GETDATE())GUN_FARK,
		 DATEDIFF(HOUR,'2002-03-08',GETDATE())SAAT_FARK,
		 DATEDIFF(MINUTE,'2002-03-08',GETDATE())DAKIKA_FARK,
		 DATEDIFF(SECOND,'2002-03-08',GETDATE())SANIYE_FARK
 */
 -->DateAdd Fonksiyonlarý
 /**	 SELECT DATEADD(YEAR,22,'2002-03-08 20:12:45:123')YEAR_, --:Yýl ekleme
		 DATEADD(DAY,22,'2002-03-08 20:12:45:123')DAY_,
		 DATEADD(HOUR,22,'2002-03-08 20:12:45:123')HOUR_,
		 DATEADD(MINUTE,22,'2002-03-08 20:12:45:123')MINUTE_,
		 DATEADD(SECOND,22,'2002-03-08 20:12:45:123')SECOND_
 */
 -->IsDate Fonksiyonlarý
 /**	 SELECT ISDATE('2002-22-22')	 --: FALSE YANI 0 DONDURUR
		 SELECT ISDATE('2002-03-02')	 --: TRUE  YANI 1 DONDURUR
 */