--CASE/WHEN
--Sadece select blogunun içinde kullanýlýr

--Yontem 1 (Dinamik view ile)
USE NORTHWND
SELECT AGEGROUP,COUNT(*) FROM(
SELECT CASE
		WHEN YASS <35 THEN'GENÇ'
		WHEN YASS BETWEEN 36 AND 55 THEN 'ORTA YASLI'
		WHEN YASS >55 THEN 'YASLI' 
		END AS AGEGROUP,*
FROM Customers
WHERE YASS IS NOT NULL
 )T
 GROUP BY AGEGROUP

 --Yontem 2 (Case i Group by'ýn içine al)
USE NORTHWND
SELECT 
CASE
		WHEN YASS <35 THEN'GENÇ'
		WHEN YASS BETWEEN 36 AND 55 THEN 'ORTA YASLI'
		WHEN YASS >55 THEN 'YASLI' 
END AS AGEGROUP,COUNT(*)
FROM Customers
WHERE YASS IS NOT NULL
GROUP BY CASE
		WHEN YASS <35 THEN'GENÇ'
		WHEN YASS BETWEEN 36 AND 55 THEN 'ORTA YASLI'
		WHEN YASS >55 THEN 'YASLI' 
END
