--> 8 MART DOGUMLU OLANLARI GETÝRÝR

SELECT * FROM LAB01 WHERE DATEPART(MONTH,BIRTHDATE)=03 AND DATEPART(DAY,BIRTHDATE)=08
ORDER BY BIRTHDATE

--> Bugün doðanlarý getir
SELECT * FROM LAB01 WHERE DATEPART(MONTH,BIRTHDATE)=DATEPART(MONTH,GETDATE()) AND DATEPART(DAY,BIRTHDATE)=DATEPART(DAY,GETDATE())
ORDER BY BIRTHDATE