SELECT * FROM LAB07
WHERE ISDATE(BIRTHDATE)=0

--VARCHAR 
UPDATE LAB07 SET BIRTHDATE = CONCAT(YEAR_,'-',MONTH_,'-',DAY_)
WHERE ISDATE(CONCAT(YEAR_,'-',MONTH_,'-',DAY_))=1

UPDATE LAB07 SET BIRTHDATE = NULLIF(BIRTHDATE, '')
--->Eger ki boþ bir string ise orayý NULL a çevir
 
--DATE
UPDATE LAB07 SET BIRTHDATE2 = BIRTHDATE
WHERE  ISDATE(BIRTHDATE)=1