--> ENG CLOCK 0 to 12
SELECT DISTINCT FORMAT(CreationDate,'hh','en-US') SAAT,COUNT(*) YORUMSAYISI FROM LAB08
GROUP BY FORMAT(CreationDate,'hh','en-US')
ORDER BY 2 DESC

-->0 to 23
SELECT DATEPART(HOUR, CreationDate)SAAT,COUNT(*) YORUMSAYISI FROM LAB08
GROUP BY DATEPART(HOUR, CreationDate)
ORDER BY 2 DESC 