select INVOICENO FATURANO,MIN(DATE_) ISLEMBASLAMA_ZAMANI,MIN(INVOICEDATE) ISLEMBITIRME_ZAMANI,
COUNT(*) URUNSAYISI,MIN(BARCODEDATE) ILKBARKOD,MAX(BARCODEDATE) SONBARKOD,DATEDIFF(SECOND,DATE_,INVOICEDATE) GECIKME_SURESI_SN from LAB04
GROUP BY INVOICENO,DATE_,INVOICEDATE

ORDER BY FATURANO  
-->INVOICEDATE Kýsmýnda Max ya da Min fark etmez
