--> Dogum yýlý telefon numarasý içinde geçenleri getir (TELNR1/TELNR2)

SELECT * FROM LAB03	WHERE TELNR1 LIKE CONCAT('%',YEAR(BIRTHDATE),'%') OR TELNR2 LIKE CONCAT('%',YEAR(BIRTHDATE),'%')

--SELECT ID,NAME_,SURNAME,BIRTHDATE,DATEPART(YEAR,BIRTHDATE)YEAR_,TELNR1 FROM LAB03	
--WHERE TELNR1 LIKE '%'+DATEPART(YEAR,BIRTHDATE)+'%'
--! ERROR
/** Msg 245, Level 16, State 1, Line 5
Conversion failed when converting the varchar value '%' to data type int.
HOW TO FIX IT*/
SELECT ID,NAME_,SURNAME,BIRTHDATE,DATEPART(YEAR,BIRTHDATE)YEAR_,TELNR1 FROM LAB03	
WHERE TELNR1 LIKE '%'+DATENAME(YEAR,BIRTHDATE)+'%'
--> DATEPART Ýnteger döndürür, DATENAME Varchar döndürür