SELECT CITY SEHIR,
SUM(DURATION) TOPLAM_BEKLEME_SURESI,
SUM(TOTALAMOUNT) TOPLAM_URUN_ADEDI,
ROUND(SUM(DURATION)/SUM(TOTALAMOUNT),2) BIR_URUN_ICIN_HARCANAN_OKUTMA_ZAMANI
FROM
(
	SELECT CITY,INVOICENO,
	MIN(BARCODEDATE) FIRST_BARCODEDATE,MAX(BARCODEDATE) LAST_BARCODEDATE,
	DATEDIFF(SECOND,MIN(BARCODEDATE),MAX(BARCODEDATE) ) DURATION,
	SUM(AMOUNT) TOTALAMOUNT,
	COUNT(ITEMCODE) ITEMCOUNT
	FROM LAB06
	--WHERE INVOICENO='10092022-000001'
	GROUP BY CITY,INVOICENO
) T
GROUP BY CITY
ORDER BY 2 DESC 