select * from LAB05

select DISTINCT CITY SEHIR,AVG(DATEDIFF(SECOND,DATE_ ,INVOICEDATE)) ORTALAMA_BEKLEME_SURESI from LAB05
GROUP BY CITY
ORDER BY 1

--> DINAMIK VIEW METHOD
SELECT CITY SEHIR,AVG(WAITTIME) ORTALAMA_BEKLEME_SURESI FROM
(
SELECT DISTINCT INVOICENO,CITY,
DATE_,INVOICEDATE,DATEDIFF(SECOND,DATE_,INVOICEDATE) WAITTIME FROM LAB05
)T
GROUP BY CITY
ORDER BY 2