TRUNCATE TABLE VEHICLEPASS
DECLARE @DATE AS DATETIME
DECLARE @VEHICLEID AS INT
DECLARE @ZONEID AS INT
DECLARE @I AS INT=0
WHILE @I<10000 
BEGIN
	DECLARE @RAND AS INT
	SET @RAND=1+RAND()*500
	SET @DATE =DATEADD(SECOND,-@RAND,GETDATE())
	SET @RAND =1+RAND()*1112247
	SET @VEHICLEID= @RAND 
	SET @RAND=1+RAND()*19
	SET @ZONEID=@RAND

	INSERT INTO VEHICLEPASS (ZONEID,VEHICLEID,DATE_)
	VALUES (@ZONEID,@VEHICLEID,@DATE)
	WAITFOR DELAY '00:00:00:010'
SET @I=@I+1
END

SELECT 
PLATE,DATE_,ZONENAME
FROM VEHICLEPASS VP
JOIN ZONES Z ON Z.ID=VP.ZONEID
JOIN VEHICLES V ON V.ID=VP.VEHICLEID 
WHERE VP.DATE_>=DATEADD(SECOND,-30,GETDATE())

 
 