USE GYSALES_RDMS_FULL

/**
ALTER PROCEDURE SP_GETITEM_INCOME
@ITEMID AS INT
AS
BEGIN

SELECT I.ID,I.BRAND,I.ITEMCODE,I.ITEMNAME,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,I.UNITPRICE,
SUM(OD.AMOUNT) TOTALAMOUNT, SUM(OD.LINETOTAL) TOTALSALE,
SUM(OD.AMOUNT)*I.UNITPRICE COST, --Maliyet
SUM(OD.LINETOTAL)/(SUM(OD.AMOUNT)*I.UNITPRICE)-1 INCOMEPERCENT --GELIR
FROM ORDERDETAILS OD
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE I.ID=@ITEMID
GROUP BY I.ID,I.BRAND,I.ITEMCODE,I.ITEMNAME,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,I.UNITPRICE

END

*/

CREATE TABLE #T(ID INT,BRAND VARCHAR(20),ITEMCODE VARCHAR(50),ITEMNAME VARCHAR(100),CATEGORY1 VARCHAR(100),CATEGORY2 VARCHAR(100),CATEGORY3 VARCHAR(100),UNITPRICE FLOAT,
TOTALAMOUNT INT, TOTALSALE FLOAT,COST FLOAT,INCOMEPERCENT FLOAT)

 -- TRUNCATE TABLE #T
---^^^^---
--CURSOR UYGULAMA1 SP YÝ GIDA KATEGORSÝNE SAHÝP BUTUN SATIRLAR ICIN ÇALIÞTIR
--EXEC SP_GETITEM_INCOME 2
--SELECT * FROM #T
--SELECT * FROM ITEMS WHERE CATEGORY1 = 'GIDA'
--INSERT INTO #T EXEC SP_GETITEM_INCOME 2

--INSERT INTO #T EXEC SP_GETITEM_INCOME 5

DECLARE @ID AS INT
DECLARE CRS CURSOR FOR SELECT ID FROM ITEMS --WHERE CATEGORY1 = 'GIDA' --SADECE IDE DEGISKENI YETERLI
OPEN CRS
FETCH NEXT FROM CRS INTO @ID
WHILE @@FETCH_STATUS = 0
BEGIN
	INSERT INTO #T EXEC SP_GETITEM_INCOME @ID
	FETCH NEXT FROM CRS INTO @ID
END
CLOSE CRS
DEALLOCATE CRS

SELECT CATEGORY1,AVG(INCOMEPERCENT) INCOMEPERCENT_ FROM #T GROUP BY CATEGORY1

DROP TABLE #T