--CURSOR
--QUERY den gelen output içinde döngü ile dönmeye yarayan yapýdýr

--SELECT ID,CITY FROM CITIES WHERE REGION = 'MARMARA'
DECLARE @ID AS INT
DECLARE @CITY AS VARCHAR(50) 

DECLARE CRS	CURSOR FOR SELECT ID,CITY  FROM CITIES WHERE REGION ='MARMARA'
OPEN CRS
-- BÝR SONRAKI SATIRA KONUMLANMAK
FETCH NEXT FROM CRS INTO  @ID,@CITY

WHILE @@FETCH_STATUS = 0 --Eðer döngünün sonuna gelinmediyse
BEGIN
	SELECT @ID,@CITY

FETCH NEXT FROM CRS INTO  @ID,@CITY
END
CLOSE CRS
DEALLOCATE CRS --DÖNGÜYÜ HAFIZADAN TEMIZLER