-- # TRIGGER ILE LOG TUTMA

--USE GYSALES_RDMS_FULL
/** ITEMS_LOG TABLE'S SCRIPT

CREATE TABLE dbo.ITEMS_LOG(
	ID int NULL,
	BRAND varchar(50) NULL,
	ITEMCODE varchar(50) NULL,
	ITEMNAME varchar(100) NULL,
	CATEGORY1 varchar(50) NULL,
	CATEGORY2 varchar(50) NULL,
	CATEGORY3 varchar(50) NULL,
	UNITPRICE float NULL,
	LOG_ACTIONTYPE varchar(50) NULL,
	LOG_DATE datetime NULL,
	LOG_USERNAME varchar(50) NULL,
	LOG_HOSTNAME varchar(50) NULL,
	LOG_PROGRAMNAME varchar(100) NULL

*/

--Üzerine yazýlan veri de DELETED de silinen de DELETED de tutulur

--#########################################################################
--# HEM UPDATE HEM DELETE TRIGGER I BIR ARADA
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
CREATE TRIGGER TRG_ITEMS_UPDATE_DELETE
ON ITEMS
AFTER UPDATE,DELETE --HEM UPDATE DE HEM DELETE DE 
AS
BEGIN
DECLARE @LOG_ACTIONTYPE AS VARCHAR(10)
DECLARE @INSERTEDCOUNT AS INT
DECLARE @DELETEDCOUNT AS INT

SELECT @INSERTEDCOUNT = COUNT(*) FROM INSERTED
SELECT @DELETEDCOUNT = COUNT(*) FROM DELETED

IF @INSERTEDCOUNT >0 AND @DELETEDCOUNT >0
 SET @LOG_ACTIONTYPE = 'UPDATE'
IF @INSERTEDCOUNT =0 AND @DELETEDCOUNT >0
 SET @LOG_ACTIONTYPE = 'DELETE'

INSERT INTO ITEMS_LOG(ID, BRAND, ITEMCODE, ITEMNAME, CATEGORY1, CATEGORY2, CATEGORY3, UNITPRICE, 
LOG_ACTIONTYPE, LOG_DATE, LOG_USERNAME, LOG_HOSTNAME, LOG_PROGRAMNAME)

SELECT ID, BRAND, ITEMCODE, ITEMNAME, CATEGORY1, CATEGORY2, CATEGORY3, UNITPRICE,
@LOG_ACTIONTYPE, GETDATE(), SUSER_NAME(),HOST_NAME(),PROGRAM_NAME()
FROM DELETED

END

-- Eðer ki tablo kopyalamak istiyorsan hedef tablo üzerinden select into yu çalýþtýr yoksa izin yok hatasý veriyor
-- GRANT INSERT ON ITEMS TO [LAPTOP-417QNQTV\M.Suleyman Guney]; -- KULLANICIYA INSERT YETKISI VERME
-- GRANT CREATE TABLE TO [LAPTOP-417QNQTV\M.Suleyman Guney]; -- KULLANICIYA CREATE TABLE YETKISI VERME

SELECT *FROM ITEMS WHERE ID=2
SELECT * FROM ITEMS_LOG WHERE ITEMNAME = 'MISIR ÖZÜ YAÐI 1LT.PET ÞÝÞE'
--DELETE FROM ITEMS WHERE ID =2

UPDATE ITEMS
SET UNITPRICE = 50, ITEMNAME = 'MISIR ÖZÜ YAÐI 1LT.PET ÞÝÞE', CATEGORY3 = 'MISIR ÖZÜ' WHERE ID=2