-- # TRIGGER ILE LOG TUTMA

--USE GYSALES_RDMS_FULL
/** ITEMS_LOG TABLE'S SCRIPT

CREATE TABLE dbo.ITEMS_LOG(
	ID int NULL,
	BRAND varchar(50) NULL,
	ITEMCODE varchar(50) NULL,
	ITEMNAME varchar(100) NULL,
	CATEGORY1 varchar(50) NULL,
	CATEGORY2 varchar(50) NULL,
	CATEGORY3 varchar(50) NULL,
	UNITPRICE float NULL,
	LOG_ACTIONTYPE varchar(50) NULL,
	LOG_DATE datetime NULL,
	LOG_USERNAME varchar(50) NULL,
	LOG_HOSTNAME varchar(50) NULL,
	LOG_PROGRAMNAME varchar(100) NULL

*/

--Üzerine yazýlan veri de DELETED de silinen de DELETED de tutulur

CREATE TRIGGER TRG_ITEMS_DELETE
ON ITEMS
AFTER DELETE
AS
BEGIN

DECLARE @LOG_ACTIONTYPE AS VARCHAR(10) = 'DELETE'

INSERT INTO ITEMS_LOG(ID, BRAND, ITEMCODE, ITEMNAME, CATEGORY1, CATEGORY2, CATEGORY3, UNITPRICE, 
LOG_ACTIONTYPE, LOG_DATE, LOG_USERNAME, LOG_HOSTNAME, LOG_PROGRAMNAME)

SELECT ID, BRAND, ITEMCODE, ITEMNAME, CATEGORY1, CATEGORY2, CATEGORY3, UNITPRICE,
@LOG_ACTIONTYPE, GETDATE(), SUSER_NAME(),HOST_NAME(),PROGRAM_NAME()
FROM DELETED
-- PROGRAM_NAME() Microsoft SQL Server Management Studio - Query

END

SELECT * FROM ITEMS WHERE ID=1
SELECT * FROM ITEMS_LOG

-- INVOICEDETAILS VE ORDERDETAILS DAKI FOREGIN KEYLER SILINMISTIR
DELETE FROM ITEMS WHERE ID=1

