SELECT '1. TAKIM' ACIKLAMA,
TEAM_LONG_NAME TAKIM_UZUN_ADI,
TEAM_SHORT_NAME TAKIM_KISA_ADI 
FROM LAB02
WHERE ID=FLOOR(1+RAND()*298)

SELECT '2. TAKIM' ACIKLAMA,
TEAM_LONG_NAME TAKIM_UZUN_ADI,
TEAM_SHORT_NAME TAKIM_KISA_ADI 
FROM LAB02
WHERE ID=FLOOR(1+RAND()*298)

  