


select
U.NAMESURNAME KULLANICIADI,
O.ID SIPARISNO,O.DATE_ TARIH,
I.ITEMCODE URUNKODU,
I.ITEMNAME URUNADI,I.BRAND MARKA,I.CATEGORY1,I.CATEGORY2
from ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN ITEMS I ON I.ID = OD.ITEMID
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A ON A.ID = O.ADDRESSID
WHERE NAMESURNAME='Nazmiye Ercan'