SET LANGUAGE TURKÝSH
SELECT DATENAME(DW,DATE_) GUNADI, 
ROUND(SUM(TOTALPRICE),1) TOPLAMTUTAR,
COUNT(ID) ADET
FROM ORDERS

GROUP BY DATENAME(DW,DATE_),DATEPART(DW,DATE_)
ORDER BY DATEPART(DW,DATE_)

