SELECT 
C.CITY SEHIR,T.TOWN ILCE,COUNT(DISTINCT A.USERID) MUSTERISAYISI
FROM TOWNS T
JOIN CITIES C ON C.ID=T.CITYID
JOIN ADDRESS A ON A.TOWNID=T.ID
WHERE C.CITY='ÝSTANBUL'
GROUP BY T.TOWN,C.CITY
ORDER BY T.TOWN


SELECT * FROM ADDRESS
