SELECT 
O.ID SIPARISNO,O.DATE_ SIPARISTARIHI,
I.ITEMCODE URUNKODU,I.ITEMNAME URUNISMI,I.BRAND MARKA,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,
OD.AMOUNT MIKTAR,OD.UNITPRICE ADETFIYAT,OD.LINETOTAL TOPLAMFIYAT

FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
--WHERE DATEPART(MONTH,DATE_)=1 AND DATEPART(YEAR,DATE_)=2022
WHERE DATE_ BETWEEN '20220101' AND '2022-01-31 23:59:59'
ORDER BY DATE_ DESC

