SELECT
O.ID,U.NAMESURNAME,C.CITY,O.DATE_ SIPARISTARIHI,
I.DATE_ KARGOLANMATARIHI,DATEDIFF(HOUR,O.DATE_,I.DATE_) SEVKEDILMESURESI_SAAT

FROM ORDERS O
JOIN USERS U ON U.ID = O.USERID
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
JOIN INVOICES I ON I.ORDERID=O.ID
ORDER BY O.ID
