
DECLARE @AVGPRICE AS FLOAT  
SELECT @AVGPRICE = ROUND(SUM(TOTALPRICE)/81,2) FROM SALES--961276,72
--Ortalama þehir cirosu belirlendi

SELECT CITY,SUM(TOTALPRICE)TOTALPRICE,IIF(SUM(TOTALPRICE)>@AVGPRICE,'Ortalamanýn üstünde','Ortalamanýn altýnda') AS STATUS_ FROM SALES
GROUP BY CITY
ORDER BY 1

--YONTEM 2 CASE / WHEN

SELECT CITY,SUM(TOTALPRICE)TOTALPRICE,
CASE
	WHEN SUM(TOTALPRICE)>@AVGPRICE THEN'Ortalamanýn üstünde'
	WHEN SUM(TOTALPRICE)=@AVGPRICE THEN 'TAM ORTALAMAYA EÞÝT'
	ELSE 'Ortalamanýn altýnda'
END AS STATUS_ FROM SALES
GROUP BY CITY
ORDER BY 1
