--Set Language turkish
SELECT 
	CASE
		WHEN CONVERT( INT,MONTH(DATE_))<10 THEN CONCAT(0,MONTH(DATE_),'.', LEFT(DATENAME(MONTH,DATE_),3))
		ELSE CONCAT(MONTH(DATE_),'.', LEFT(DATENAME(MONTH,DATE_),3))

	END AS MONTH_
		,ROUND(SUM(TOTALPRICE),0) TOTALPRICE FROM SALES
GROUP BY 
	CASE
		WHEN CONVERT( INT,MONTH(DATE_))<10 THEN CONCAT(0,MONTH(DATE_),'.', LEFT(DATENAME(MONTH,DATE_),3))
		ELSE CONCAT(MONTH(DATE_),'.', LEFT(DATENAME(MONTH,DATE_),3))
	END
ORDER BY 1