select * from LAB06
ORDER BY ORDERNO DESC

ALTER TABLE LAB06 ADD ORDERNO2 VARCHAR(17)

UPDATE LAB06 SET ORDERNO=CONCAT(CONVERT(VARCHAR(8),DATE_,112),'-',REPLICATE('0',8-LEN(ID)),ID)

UPDATE LAB06 SET ORDERNO2=CONCAT(FORMAT(DATE_,'yyyyMMdd'),'-',REPLICATE('0',8-LEN(ID)),ID)
-->yy : Yıl	 MM : Ay	dd : Gün		mm: Dakikayı ifade eder		