--> SELECT * INTO ÝLE BOÞ TABLO
SELECT TOP 0 * INTO USERS2 FROM USERS
--> ICINDEKI HIÇBIR VERIYI ALMADAN OLUSTURUR DESIGNI PK HARIC AYNI

SELECT * INTO USERS2 FROM USERS WHERE 1=0
--> YA DA OLAMYACAK BÝR ÞART VERIRSEK DE OLUR
