SELECT U1.ID, U1.NAMESURNAME, INFOM.TARIH ENSON_ALISVERIS_TARIHI,INFOM.SEHIR, INFOM.ACIKADRES  FROM USERS U1
CROSS APPLY
(
	SELECT TOP 1 CONVERT(DATE,MAX(DATE_))TARIH, C.CITY SEHIR, A.ADDRESSTEXT ACIKADRES FROM ORDERS O
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	JOIN CITIES C ON C.ID=A.CITYID
	JOIN USERS U ON U.ID=O.USERID
	WHERE U.ID = U1.ID
	GROUP BY C.CITY,A.ADDRESSTEXT,O.DATE_
	ORDER BY O.DATE_ DESC
)INFOM

--> Cross Apply sayesinde kod kalabalığının çnüne geçileblinir
		--> Order by kısmını unutma durumnda gelen veride hata payı bulunur
