
SELECT * INTO USERSYEDEK FROM USERS

DELETE FROM USERS
WHERE BIRTHDATE BETWEEN '19500101' AND '19601231'
--> YANIÞLIKLA HESPINI SILERSEN [ DELETE FROM USERS ]

SELECT * FROM USERS
--> KURTARMAK ÝÇÝN

SET IDENTITY_INSERT USERS ON
INSERT INTO USERS( [ID], [USERNAME_], [PASSWORD_], [NAMESURNAME], [EMAIL], [GENDER], [BIRTHDATE], [CREATEDDATE], [TELNR1], [TELNR2])
SELECT [ID], [USERNAME_], [PASSWORD_], [NAMESURNAME], [EMAIL], [GENDER], [BIRTHDATE], [CREATEDDATE], [TELNR1], [TELNR2] 
FROM USERSYEDEK

--> HATA ALINIR
--Cannot insert explicit value for identity column in table 'USERS' when IDENTITY_INSERT is set to OFF.

--> ÇÖZÜMÜ 
SET IDENTITY_INSERT USERS ON