SELECT DISTINCT I1.CATEGORY1,
(
SELECT TOP 1 I.BRAND FROM ORDERDETAILS OD
JOIN ITEMS I ON OD.ITEMID = I.ID
WHERE I.CATEGORY1= I1.CATEGORY1
GROUP BY I.BRAND
ORDER BY SUM(OD.LINETOTAL) DESC
)En_Fazla_Marka,
(
SELECT TOP 1 ROUND(SUM(OD.LINETOTAL),0) FROM ORDERDETAILS OD
JOIN ITEMS I ON OD.ITEMID = I.ID
WHERE I.CATEGORY1= I1.CATEGORY1
GROUP BY I.BRAND
ORDER BY SUM(OD.LINETOTAL) DESC
)Tutar,
(
SELECT TOP 1 I.BRAND FROM ORDERDETAILS OD
JOIN ITEMS I ON OD.ITEMID = I.ID
WHERE I.CATEGORY1= I1.CATEGORY1
GROUP BY I.BRAND
ORDER BY SUM(OD.LINETOTAL) ASC
)En_Az_Marka,
(
SELECT TOP 1 ROUND(SUM(OD.LINETOTAL),0) FROM ORDERDETAILS OD
JOIN ITEMS I ON OD.ITEMID = I.ID
WHERE I.CATEGORY1= I1.CATEGORY1
GROUP BY I.BRAND
ORDER BY SUM(OD.LINETOTAL) ASC
)Tutar

FROM ITEMS I1




