select C.CITY,
(
SELECT TOP 1  I.CATEGORY2 FROM ORDERS O
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN ORDERDETAILS OD ON OD.ORDERID  =O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE A.CITYID = C.ID
GROUP BY I.CATEGORY2
ORDER BY SUM(OD.LINETOTAL) DESC
)En_Fazla_Satis_Yapan_Kategori,
(
SELECT TOP 1  SUM(OD.LINETOTAL) FROM ORDERS O
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN ORDERDETAILS OD ON OD.ORDERID  =O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE A.CITYID = C.ID
GROUP BY I.CATEGORY2
ORDER BY SUM(OD.LINETOTAL) DESC
)Tutar,
(
SELECT TOP 1  I.CATEGORY2 FROM ORDERS O
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN ORDERDETAILS OD ON OD.ORDERID  =O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE A.CITYID = C.ID
GROUP BY I.CATEGORY2
ORDER BY SUM(OD.LINETOTAL)
)En_Az_Satis_Yapan_Kategori,
(SELECT TOP 1  SUM(OD.LINETOTAL) FROM ORDERS O
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN ORDERDETAILS OD ON OD.ORDERID  =O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE A.CITYID = C.ID
GROUP BY I.CATEGORY2
ORDER BY SUM(OD.LINETOTAL))En_Az_Tutar
from CITIES C