--> WAREHOUSE VERIAMBARI OLUSTURMA
--> SUTUN ÝSÝMLERÝ BENZERSÝZ OLMALI (2832850 rows affected)
SELECT 
O.ID ORDERID,O.DATE_ ORDERDATE,O.TOTALPRICE,O.STATUS_,
U.ID USERID,U.BIRTHDATE,U.CREATEDDATE,U.USERNAME_,U.NAMESURNAME,U.EMAIL,U.GENDER,U.TELNR1,U.TELNR2,
C.CITY,T.TOWN,D.DISTRICT,A.ID ADDRESSID,A.POSTALCODE,A.ADDRESSTEXT,
I.ID ITEMID,I.ITEMCODE,I.ITEMNAME,I.BRAND,I.UNITPRICE ITEMUNITPRICE,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,
OD.ID ORDERDETAILID, OD.AMOUNT,OD.UNITPRICE ORDERUNITPRICE,OD.LINETOTAL,
IV.ID INVOICEID,IV.DATE_ INVOICEDATE,IV.INVOICENO,IV.CARGOFICHENO

INTO SALES

FROM ORDERS O
	JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	JOIN USERS U ON U.ID=O.USERID
	JOIN ADDRESS A ON A.ID= O.ADDRESSID
	JOIN CITIES C ON C.ID = A.CITYID
	JOIN TOWNS T ON T.ID = A.TOWNID
	JOIN DISTRICTS D ON D.ID = A.DISTRICTID

	JOIN ITEMS I ON I.ID=OD.ITEMID
	JOIN INVOICES IV ON IV.ORDERID=O.ID
	JOIN INVOICEDETAILS IVD ON IVD.INVOICEID=IV.ID

--> HER GECE SILIP TEKRAR YAPILIR DROP TABLE SALES
	SELECT * FROM SALES
	-->SONRASINDA 
ISNERT INTO SALES 
SELECT 
O.ID ORDERID,O.DATE_ ORDERDATE,O.TOTALPRICE,O.STATUS_,
U.ID USERID,U.BIRTHDATE,U.CREATEDDATE,U.USERNAME_,U.NAMESURNAME,U.EMAIL,U.GENDER,U.TELNR1,U.TELNR2,
C.CITY,T.TOWN,D.DISTRICT,A.ID ADDRESSID,A.POSTALCODE,A.ADDRESSTEXT,
I.ID ITEMID,I.ITEMCODE,I.ITEMNAME,I.BRAND,I.UNITPRICE ITEMUNITPRICE,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,
OD.ID ORDERDETAILID, OD.AMOUNT,OD.UNITPRICE ORDERUNITPRICE,OD.LINETOTAL,
IV.ID INVOICEID,IV.DATE_ INVOICEDATE,IV.INVOICENO,IV.CARGOFICHENO

FROM ORDERS O
	JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	JOIN USERS U ON U.ID=O.USERID
	JOIN ADDRESS A ON A.ID= O.ADDRESSID
	JOIN CITIES C ON C.ID = A.CITYID
	JOIN TOWNS T ON T.ID = A.TOWNID
	JOIN DISTRICTS D ON D.ID = A.DISTRICTID

	JOIN ITEMS I ON I.ID=OD.ITEMID
	JOIN INVOICES IV ON IV.ORDERID=O.ID
	JOIN INVOICEDETAILS IVD ON IVD.INVOICEID=IV.ID
