/**
use TSQL_LAB_LOOPS
select * from customers
*/
--SELECT * FROM SURNAMES --798
--SELECT * FROM NAMES --610
--SELECT * FROM CITIES --81


--ALTER TABLE CUSTOMERS
---SET ID IDENTITY(1,1)


DECLARE @I AS INT=0
WHILE @I<10000
BEGIN
		DECLARE @RANDS AS INT = 1+RAND()*797,-- surname id
				@RANDN AS INT = 1+RAND()*609,-- name id
				@RANDC AS INT = 1+RAND()*80,-- city id
				@RANDD AS INT = RAND()*360*50--date id

		DECLARE @NAME AS VARCHAR(100),@SURNAME AS VARCHAR(100),@CITY AS VARCHAR(100),@GENDER AS CHAR(1),
				@BIRTHDATE AS DATE = '1950-01-01'

		SELECT @NAME=NAME_,@GENDER=GENDER FROM NAMES
			WHERE ID = @RANDN

		SELECT @SURNAME=SURNAME FROM SURNAMES
			WHERE ID = @RANDS

		SELECT @CITY=CITY FROM CITIES
			WHERE ID = @RANDC
		
		IF DATEADD(DAY,@RANDD,@BIRTHDATE)<GETDATE()
		BEGIN
			SET @BIRTHDATE= DATEADD(DAY,@RANDD,@BIRTHDATE)
		END
		


		--SELECT @NAME NAME_,@SURNAME SURNAME,CONCAT(@NAME,' ',@SURNAME)NAMESURNAME, @GENDER GENDER, @CITY CITY ,@BIRTHDATE BIRTHDATE
		INSERT INTO CUSTOMERS(NAME_,SURNAME,NAMESURNAME,GENDER,BIRTHDATE,CITY) 
		VALUES(@NAME,@SURNAME,CONCAT(@NAME,' ',@SURNAME),@GENDER,@BIRTHDATE,@CITY)

		SET @I = @I+1
END

SELECT * FROM CUSTOMERS

-- Company only sells products to customers who are older than 18 years old.
-- Select all customers who are older than 18 years old based on their birthdate
SELECT *
FROM CUSTOMERS
WHERE BIRTHDATE < DATEADD(YEAR, -18, GETDATE());