DECLARE @I AS INT=0
WHILE @I<1000
BEGIN
		DECLARE @DEVICEID AS INT=1,
				@LASTVALUE AS FLOAT,
				@LASTDATE AS DATETIME,
				@CURRENTVALUE AS FLOAT,
				@DATE AS DATETIME

		DECLARE @RAND AS FLOAT = 2*(-0.5 + RAND()), -- 1 ile -1 arasýnda sayý döndürür
				@RAND2 AS INT = 15+(RAND()*45) -- 15 ila 60 arasýnda sayý döndürür

		SET @DEVICEID = 1+RAND()*99 -- 1 ila 100 arasýnda sayý dondurur

		SELECT @LASTVALUE=LASTVALUE, @LASTDATE=LASTDATE FROM THERMOMETERS
		WHERE ID=@DEVICEID

		SET @CURRENTVALUE = ROUND(@LASTVALUE + @RAND,2)
		SET @DATE =DATEADD(SECOND,@RAND2,@LASTDATE)

		--Oluþturulan veriyi görmek için
		--SELECT @DEVICEID DEVICEID, @LASTVALUE LASTVALUE, @LASTDATE LASTDATE, @CURRENTVALUE CURRENTVALUE, @DATE DATE_

		INSERT INTO THERMOVALUES VALUES(@DEVICEID, @CURRENTVALUE, @DATE)
		UPDATE THERMOMETERS SET LASTDATE=@DATE,LASTVALUE=@CURRENTVALUE WHERE ID = @DEVICEID

		SET @I=@I+1
END
--SELECT * FROM THERMOMETERS

--SELECT * FROM THERMOVALUES
--TRUNCATE TABLE THERMOVALUES