SELECT * FROM USERS--9670
SELECT * FROM ORDERS --BOÞ
SELECT * FROM ORDERDETAILS
SELECT * FROM ITEMS --1367
SELECT * FROM ADDRESS--24270

DECLARE @I AS INT
WHILE @I<1000
BEGIN

--ORDERS TABLE
DECLARE @USERID AS INT,
		@RANDU AS INT=1+RAND()*9669, 
		@ADDRESSID AS INT,
		--@RANDA AS INT=1+RAND()*24268, --Gerek Kalmadý
		@DATE AS DATETIME='2022-01-01',
		@RANDD AS INT = RAND()*60*60*24*365,--SANIYE 15552000 --> 86400*365
		@STATUS AS TINYINT, -- 1 YA DA 0 OLARAK IIF ILE AYARLA USERID IS NOT NULL ILE
		@TOTALPRICE AS FLOAT


SET @DATE = DATEADD(SECOND,@RANDD,@DATE)
SELECT @USERID=ID FROM USERS WHERE ID=@RANDU
SELECT @ADDRESSID=ID FROM ADDRESS WHERE USERID=@USERID ORDER BY NEWID()
SELECT @STATUS = IIF(@USERID IS NOT NULL AND @ADDRESSID IS NOT NULL,1,0) --AND @TOTALPRICE IS NOT NULL 

--SELECT * FROM ADDRESS WHERE ID = @ADDRESSID


--ORDER DETAILS TABLE
DECLARE @ORDERID AS INT = @@IDENTITY,
		@RANDORDER AS INT = 1+RAND()*9999,
		@ITEMID AS INT,
		@RANDITEM AS INT = 1+RAND()*1366,
		@AMOUNT AS INT,
		@RANDAMOUNT AS INT = 1+RAND()*9,-- 1 ila 10 arasý
		@UNITPRICE AS FLOAT,
		@LINETOTAL AS FLOAT


SELECT @ITEMID=ID, @UNITPRICE=UNITPRICE FROM ITEMS WHERE ID = @RANDITEM
SET @LINETOTAL = @UNITPRICE * @RANDAMOUNT

SET @TOTALPRICE = (SELECT SUM(LINETOTAL) FROM ORDERDETAILS WHERE ID=@ORDERID)


--SELECT @TOTALPRICE = SUM(@LINETOTAL) FROM ORDERS WHERE @ORDERID=ID
UPDATE ORDERS SET TOTALPRICE = (SELECT SUM(LINETOTAL) FROM ORDERDETAILS WHERE ORDERID=ORDERS.ID)
WHERE ID=@ORDERID

--CHECK
SELECT @USERID USERID, @ADDRESSID ADDRESSID, @DATE DATE_,@STATUS STATUS,@TOTALPRICE TOTALPRICE
SELECT @ORDERID ORDERID, @ITEMID ITEMID, @RANDAMOUNT AMOUNT, @UNITPRICE UNITPRICE, @LINETOTAL LINETOTAL

--PUT INTO
INSERT INTO ORDERS VALUES(@USERID,@ADDRESSID,@DATE,@STATUS,@TOTALPRICE)


SET @I=@I+1
END

/**
TRUNCATE TABLE ORDERS
TRUNCATE TABLE ORDERDETAILS
*/
