use GYSALES_RDMS_FULL
--select * from ITEMS

ALTER FUNCTION dbo.FNITEMINFO
(	
	-- Add the parameters for the function here
	@ITEMID AS INT
)
RETURNS TABLE 
AS
RETURN 
(
	-- Add the SELECT statement with parameter references here
	SELECT I.ITEMCODE, I.ITEMNAME, SUM(OD.LINETOTAL) TOTALSALE, SUM(OD.AMOUNT) TOTALAMOUNT,
	MIN(OD.UNITPRICE) MINPRICE, MAX(OD.UNITPRICE) MAXPRICE,ROUND(AVG(OD.UNITPRICE),2) AVGPRICE
	FROM ITEMS I
	JOIN ORDERDETAILS OD ON OD.ITEMID = I.ID
	WHERE I.ID = @ITEMID
	GROUP BY I.ITEMCODE, I.ITEMNAME
) 
GO 
		
SELECT I.ITEMCODE,I.ITEMNAME,ITEMINFO.MINPRICE ENDUSUK_FIYAT, ITEMINFO.MAXPRICE ENYUKSEK_FIYAT, ITEMINFO.AVGPRICE ORTLAMA_FIYAT FROM ITEMS I
CROSS APPLY(SELECT * FROM dbo.FNITEMINFO(I.ID))ITEMINFO
ORDER BY 1
--CROSS APPLY :
--  is used to apply a table-valued function (dbo.FNITEMINFO) to each row returned by the ITEMS table (I).

--Multi Statement Table Valued Function