ALTER FUNCTION dbo.GETUSERINFO(@USERID INT)
RETURNS
@RESULT TABLE
(
AD VARCHAR (100),
SOYAD VARCHAR (100),
SONSEHIR VARCHAR (100),
ENCOKKULLANILAN_SEHIR VARCHAR (100),
SONRUNAD VARCHAR (100)
)
AS
BEGIN
	INSERT INTO @RESULT(AD, SOYAD)--,SONSEHIR,ENCOKKULLANILAN_SEHIR,SONRUNAD)
	SELECT * FROM  string_split((SELECT NAMESURNAME FROM USERS WHERE ID= @USERID),' ',1) WHERE ordinal=  1,
	(SELECT * FROM  string_split((SELECT NAMESURNAME FROM USERS WHERE ID= @USERID),' ',1) WHERE ordinal=  2))
	--(SELECT ADDRESSID,MAX(DATE_) FROM ORDERS WHERE USERID = @USERID)
	--(SELECT *FROM ORDERDETAILS)--SONURUN



	RETURN
END
GO


SELECT * FROM USERS
SELECT * FROM dbo.GETUSERINFO(1)
