
ALTER FUNCTION dbo.FNAGES(@BIRTHDATE DATE,@ID INT)
RETURNS TABLE
AS
RETURN
(
SELECT DATEDIFF(YEAR,@BIRTHDATE,GETDATE()) AGE,
CASE
	WHEN DATEDIFF(YEAR,@BIRTHDATE,GETDATE())BETWEEN 10 AND 19 THEN '10-19 ARASI'
	WHEN DATEDIFF(YEAR,@BIRTHDATE,GETDATE())BETWEEN 20 AND 29 THEN '20-29 ARASI'
	WHEN DATEDIFF(YEAR,@BIRTHDATE,GETDATE())BETWEEN 30 AND 40 THEN '30-40 ARASI'
	WHEN DATEDIFF(YEAR,@BIRTHDATE,GETDATE())>40 THEN '40 TAN BÜYÜK'
END AS AGEGROUP FROM PLAYER WHERE ID=@ID
)

SELECT *, FNAGES.AGE,FNAGES.AGEGROUP FROM PLAYER P
CROSS APPLY (SELECT * FROM dbo.FNAGES(P.BIRTHDATE,P.ID)) AS FNAGES
